-- 우리가족 건강관리 Cloud V1.0 - Supabase schema
-- Supabase Dashboard > SQL Editor에서 한 번 실행하세요.

create table if not exists public.health_settings (
  id bigint generated by default as identity primary key,
  family_id text not null,
  key text not null,
  value text,
  created_at timestamptz not null default now(),
  unique (family_id, key)
);

create table if not exists public.health_lab_records (
  id bigint generated by default as identity primary key,
  family_id text not null,
  exam_date date not null,
  total_chol double precision,
  ldl double precision,
  hdl double precision,
  triglyceride double precision,
  fasting_glucose double precision,
  hba1c double precision,
  cpk double precision,
  bilirubin double precision,
  ast_got double precision,
  alt_gpt double precision,
  wbc double precision,
  mpv double precision,
  vitamin_d double precision,
  height_cm double precision,
  weight_kg double precision,
  systolic integer,
  diastolic integer,
  note text default '',
  source text default 'manual',
  created_at timestamptz not null default now(),
  unique (family_id, exam_date)
);

create table if not exists public.health_events (
  id bigint generated by default as identity primary key,
  family_id text not null,
  event_date date not null,
  category text default '기타',
  event_text text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.family_health_logs (
  id bigint generated by default as identity primary key,
  family_id text not null,
  record_date date not null,
  person text not null,
  section text not null,
  category text default '',
  value1 double precision,
  value2 double precision,
  value3 text default '',
  note text default '',
  created_at timestamptz not null default now()
);

create index if not exists idx_lab_family_date on public.health_lab_records(family_id, exam_date);
create index if not exists idx_event_family_date on public.health_events(family_id, event_date);
create index if not exists idx_log_family_person_section_date on public.family_health_logs(family_id, person, section, record_date);

-- 앱은 Streamlit 서버의 Secret Key로만 접근합니다.
-- 브라우저의 anon key 접근은 막아 두기 위해 RLS를 켜고 public policy는 만들지 않습니다.
alter table public.health_settings enable row level security;
alter table public.health_lab_records enable row level security;
alter table public.health_events enable row level security;
alter table public.family_health_logs enable row level security;
